FROM python:3.11-alpine

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

RUN pip install --upgrade pip setuptools wheel
RUN pip install gunicorn==20.1.*

COPY requirements.txt /app
RUN pip install -r requirements.txt

COPY . /app/

ARG MAX_COURSE_ATTEMPTS=""
ARG FERNET_KEY=""
ARG FABMAN_API_KEY=""
ARG CLASSMARKER_WEBHOOK_SECRET=""
ARG FLASK_SECRET_KEY=""
ARG MAIL_USERNAME=""
ARG MAIL_PASSWORD=""
ARG VERIFY_CLASSMARKER_REQUESTS=""
ARG SECRET_KEY="42"
ARG MAIL_SERVER=""
ARG MAIL_PORT=""
ARG MAIL_USERNAME=""
ARG MAIL_PASSWORD=""
ARG MAIL_USE_TLS=""
ARG BE_ENV="prod"

EXPOSE 8000

CMD gunicorn --log-level=debug --workers=2 --bind=[::]:8000 'main_run:main_loop()'
