import os


MAX_COURSE_ATTEMPTS = os.getenv("MAX_COURSE_ATTEMPTS", 3)
FERNET_KEY = os.getenv("FERNET_KEY")
FABMAN_API_KEY = os.getenv("FABMAN_API_KEY")
CRONJOB_TOKEN = os.getenv("CRONJOB_TOKEN")
CLASSMARKER_WEBHOOK_SECRET = os.getenv("CLASSMARKER_WEBHOOK_SECRET")
FLASK_SECRET_KEY = os.getenv("SECRET_KEY")
MAIL_USERNAME = os.getenv("MAIL_USERNAME")
MAIL_PASSWORD = os.getenv("MAIL_PASSWORD")
FABLAB_SUPPORT_EMAIL = os.getenv("FABLAB_SUPPORT_EMAIL")
VERIFY_CLASSMARKER_REQUESTS = os.getenv("VERIFY_CLASSMARKER_REQUESTS")
TRACK_TIME = os.getenv("TRACK_TIME")
COURSES_WEB_PRIVATE_KEY = os.getenv("COURSES_WEB_PRIVATE_KEY")
